name: IndexNow Notification

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 최신 버전으로 업데이트

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Node.js 버전 설정
      with:
        node-version: '20'

    - name: Notify IndexNow
      env:
        API_KEY: ${{ secrets.INDEXNOW_KEY }}
      run: |
        response=$(curl -X POST "https://www.bing.com/indexnow" \
          -H "Content-Type: application/json" \
          -d '{
                "host": "kj1241.github.io",
                "key": "'${API_KEY}'",
                "keyLocation": "https://kj1241.github.io/key.txt",
                "urlList": ["https://kj1241.github.io"]
              }')
        echo "IndexNow response: $response"
