name: IndexNow Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate URL List
      run: |
        git diff --name-only HEAD~1 HEAD | while read filename; do
          echo "https://example.com/$filename" >> urls.txt
        done

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger IndexNow
      env:
        API_KEY: ${{ secrets.INDEXNOW_API_KEY }}
      run: |
        URLS=$(cat urls.txt | jq -R -s -c 'split("\n")[:-1]')
        curl -X POST 'https://api.indexnow.org/indexnow' \
        -H 'Content-Type: application/json' \
        -d "{
              \"host\": \"example.com\",
              \"key\": \"${{ secrets.INDEXNOW_API_KEY }}\",
              \"urlList\": $URLS
            }"
