name: IndexNow API Trigger

on:
  push:
    branches:
      - main  # 원하는 브랜치를 지정하세요

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send POST request to IndexNow API
        env:
          HOST: kj1241.github.io
          KEY: ${{ secrets.INDEXNOW_KEY }}
          KEY_LOCATION: https://kj1241.github.io/${{ secrets.INDEXNOW_KEY }}.txt
        run: |
          URL_LIST=$(cat <<EOF
          [
            "https://kj1241.github.io/",
            "https://kj1241.github.io/sitemap.xml"
          ]
          EOF
          )

          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://api.indexnow.org/indexnow" \
          -H "Content-Type: application/json; charset=utf-8" \
          -d '{
            "host": "'"${HOST}"'",
            "key": "'"${KEY}"'",
            "keyLocation": "'"${KEY_LOCATION}"'",
            "urlList": '"${URL_LIST}"'
          }')

          # Split the response and the HTTP status code
          HTTP_BODY=$(echo "$RESPONSE" | sed '$d')
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)

          echo "Response Body: $HTTP_BODY"
          echo "HTTP Status: $HTTP_STATUS"
