name: IndexNow Notification

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notify IndexNow
      env:
        API_KEY: ${{ secrets.INDEXNOW_KEY }}
      run: |
        curl -X POST "https://www.bing.com/indexnow" \
        -H "Content-Type: application/json" \
        -d '{
              "host": "kj1241.github.io",
              "key": "'${API_KEY}'",
              "keyLocation": "https://kj1241.github.io/key.txt",
              "urlList": ["https://kj1241.github.io"]
            }'