name: Secret Debugging Workflow

on:
  push:
    branches:
      - main  # 원하는 브랜치를 지정하세요

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save tttt Secret to File
        run: echo "${{ secrets.tttt }}" > secret_value.txt

      - name: Read and Print tttt Secret from File
        run: cat secret_value.txt